language: node_js
node_js:
  - "9"
dist: trusty
services:
  - postgresql
before_script:
  - psql -c 'create database database_test;' -U postgres
  - yarn -g sequelize-cli
env: 
  - NODE_ENV=ci
cache: yarn
before_install: cd server
install: 
  - yarn
script:
  - sequelize db:migrate
  - yarn test

