language: node_js
node_js:
  - "9"
dist: trusty
services:
  - postgresql
before_script:
  - psql -c 'create database database_test;' -U postgres
env: 
  - NODE_ENV=test
cache: yarn
before_install: cd server
install: 
  - yarn
script:
  - yarn test

