export default {
  API: 'API',
  RESPONSE_MSG: 'RESPONSE_MSG',

  RESPONSE_ERROR: 'RESPONSE_ERROR',
  RESET_ERROR: 'RESET_ERROR',
  INVALID_TOKEN: 'INVALID_TOKEN',

  REQUEST_START: 'REQUEST_START',
  REQUEST_END: 'REQUEST_END'
};